polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('list', views.list, name="list"),
    path('new-question', views.new_question, name="new-question"),
    path('add-vote', views.add_vote, name="vote"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('detail/<int:id>/resultat', views.result, name="results"),
]

tutop/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('polls.urls')),

    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models
from django.shortcuts import reverse


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.question_text}'

    def get_absolute_url(self):
        return reverse("polls:detail", kwargs={"id": self.pk})

    def get_total(self):
        count = 0
        for choice in self.choices.all():
            count += choice.votes
        return count


class Choice(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="choices"
    )
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.choice_text}'

polls/forms.py
from django.forms import ModelForm
from polls.models import Question


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']

polls/views/deg.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse

from polls.models import Question, Choice


def new_choice(request):
    id_question = request.POST['question_id']
    choice = request.POST['new_choice']

    Choice.objects.create(
        question=Question.objects.get(id=id_question),
        choice_text=choice
    )
    return redirect('polls:detail', id_question)


def add_vote(request):
    if request.method == 'POST':
        id_question = request.POST['question_id']
        id_choice = request.POST['choice_id']
        if request.POST['new_choice']:
            return new_choice(request)
        if id_choice and id_question:
            response = redirect('polls:detail', id_question)
            if request.COOKIES.get("vote_" + id_question) is None:
                choice = Choice.objects.get(id=id_choice)
                choice.votes += 1
                choice.save()
                response.set_cookie("vote_" + str(id_question), "Voted")
                messages.success(request, "Vote comptabilisé")
            else:
                messages.warning(request, "T'a déjà voté FDP (- kenji)")
            return response
    messages.error(request, "Erreur de formulaire")
    return redirect('polls:list')

polls/views/propre.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse

from polls.models import Question, Choice
from polls.forms import QuestionForm


def list(request):
    questions = Question.objects.all()

    context = {
        'questions': questions,
        'form': QuestionForm(),
    }
    return render(request, 'polls/list.html', context)


def detail(request, id):
    question = Question.objects.get(id=id)

    context = {
        'question': question,
    }
    return render(request, 'polls/details.html', context)


def new_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Question ajoutée")
        else:
            messages.error(request, "Formulaire invalide")
    else:
        messages.error(request, "Formulaire non trouvé")
    return redirect('polls:list')


def result(request, id):
    question = Question.objects.get(id=id)
    choices = question.choices.all().order_by('-votes')
    choice_list = []
    for choice in choices:
        choice_list.append({
            'value': choice.choice_text,
            'count': choice.votes,
            'width': choice.votes / question.get_total() * 100,
        })

    context = {
        'question': question,
        'choices': choice_list,
    }
    return render(request, 'polls/results.html', context)

polls/templates/polls/details.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="offset-md-3 col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-white">
                {{question}}
            </div>
            <div class="card-body">
                <div>
                    Votes totaux : {{question.get_total}}
                </div>
                <form action="{% url 'polls:vote' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="question_id" value="{{question.id}}">
                    <ul class="list-unstyled">
                    {% for choice in question.choices.all %}
                        <li>
                            <button
                                class="btn bg-secondary text-white mt-2 w-100"
                                type='submit'
                                name="choice_id"
                                value="{{choice.id}}">
                                {{choice}}
                            </button>
                        </li>
                    {% endfor %}
                        <li>
                            <div class="input-group mb-2 mr-sm-2">
                                <input
                                    class="form-control mt-2 w-100"
                                    type='text'
                                    name="new_choice"
                                    placeholder="Nouveau choix">
                                <button
                                    class="btn btn-dark mt-2"
                                    type="submit"
                                    name="choice_id"
                                    value="_">
                                    +
                                </button>
                            </div>
                        </li>
                    </ul>
                </form>
                <div class="text-right">
                    <a href="{% url 'polls:results' question.id %}" class="btn btn-primary">Voir résultats</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="offset-md-3 col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-white">
                Liste des questions
            </div>
            <div class="card-body">
                <form action="{% url 'polls:new-question' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-2 mr-sm-2">
                        <input
                            class="form-control mt-2 w-100"
                            type='text'
                            name="{{form.question_text.name}}"
                            placeholder="Nouvelle question">
                        <button
                            class="btn btn-dark mt-2"
                            type="submit">
                            +
                        </button>
                    </div>
                </form>
                {% for question in questions %}
                    <a href="{{question.get_absolute_url}}">
                        <div class="border p-1 mt-2">
                            {{question}} [{{question.get_total}}]
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="offset-md-3 col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-white">
                {{question}}
            </div>
            <div class="card-body">
                {% for choice in choices %}
                    <div class="progress mt-2">
                        <div
                            class="progress-bar"
                            role="progressbar"
                            style="width: {{choice.width}}%;"
                            aria-valuenow="{{choice.count}}"
                            aria-valuemin="0"
                            aria-valuemax="100">
                            {{choice.value}}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

tutop/templates/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Polls</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    </head>
    <body>
        <div class="container">
            <div class="text-center mt-2 bg-dark">
                <h2 class="text-white p-2">Questions !</h2>
            </div>
            <a href="{% url 'polls:list' %}">> Liste des Questions</a>
            <{% block content %}
            {% endblock %}>
        </div>
        <script
			src="https://code.jquery.com/jquery-3.4.1.min.js"
			integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

        {% if messages %}
            <script>
            {% for message in messages %}
                toastr.{{ message.tags }}('{{ message }}');
            {% endfor %}
            </script>
        {% endif %}
    </body>
</html>